### ISSUE TITLE
Broke after moving sidebar

### ISSUE THREAD

**Issue by tekord** [stevium/iceterm#3] opened 2020-06-16 16:26 UTC
Tried to move IdeaConEmu Terminal from right bar to the bottom bar and it broke. Here is a short video: https://dl.dropboxusercontent.com/s/f3js97tqrk4d11p/2020-06-16_20-24-44_%25pn.mp4

**Comment by stevium** [comment] 2020-06-16 17:23
I can see an issue with dragging indeed. 

The problem is when the tab panel disappears, the HWND to which  ConEmu is attached gets destroyed, and ConEmu closes. 

Thanks for reporting, I will try to provide a fix by the end of this week.

**Comment by stevium** [comment] 2020-07-10 20:58
@tekord Sorry for the late update, but I haven't had any free time until now. The issue should be now fixed and deployed to the plugin page. Feel free to try it out, and let me know if you have any other issues.

**Closed as completed by stevium** 2020-07-10 20:58 UTC
Labels: bug

**Comment by tekord** [comment] 2020-07-10 21:03
@stevium thanks! gonna try it next week.
